// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Login test', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Login test', async function() {
    await driver.get("http://localhost:4000/login")
    await driver.manage().window().setRect({ width: 1294, height: 1032 })
    await driver.findElement(By.name("email")).click()
    await driver.findElement(By.name("email")).sendKeys("a@gmail.com")
    await driver.findElement(By.name("password")).click()
    await driver.findElement(By.name("password")).sendKeys("123456")
    await driver.findElement(By.css(".btnLogin")).click()
  })
})
